// src/config/tenantTextConfig.js

export const TENANT_TEXT = {
  bank: {
    roleLabels: {
      ORGANIZATION_ADMIN: "Organization Admin",
    },
    sidebar: {
      branches: "Branches",
      branchAdmins: "Branch Admins",
    },
    organizations: {
      pageTitle: "Organizations",
      pageSubtitle: "Manage and view all registered organizations",
      addLabel: "Add Bank",
      tableTitle: "Registered Networks",
    },
    branches: {
      pageTitle: "Branch Management",
      pageSubtitle: "Manage and view all branches for your network",
      tableTitle: "Bank Branches",
    },
    orgAdminPages: {
      addService: {
        title: "Add Service (Bulk)",
        subtitle: "Create a service for multiple branches at once",
        selectLabel: "Select Branches (Hold Ctrl/Cmd to select multiple)",
        selectedText: "branches",
        emptySelectionError: "Please select at least one branch.",
      },
      services: {
        title: "Services",
        subtitle: "Manage services across your branches",
        addBtn: "+ Add Service",
        noData: "No branches found",
        divisionServicesTitle: "Organization Services",
        noDivisionServices: "No organization services found.",
        branchCol: "Branch Name",
        noBranchesOffer: "No branches offer this service.",
      },
      dashboard: {
        pageTitle: "Dashboard Overview",
        roleLabel: "Organization Admin",
        cards: {
          branches: "Branches",
          requests: "Pending Requests",
          services: "Services",
          workforce: "Workforce",
        },
        charts: {
          statusTitle: "Branch Status Overview",
          statusSubtitle: "Breakdown of branch lifecycle status across the organization.",
          topTitle: "Top Branches by Staff Size",
          topSubtitle: "Compare service volume for the busiest branches.",
        },
        quickActions: {
          title: "Quick Actions",
          subtitle: "Create and manage core organization records.",
          addBranch: "+ Add New Branch",
          addAdmin: "+ Add Branch Admin",
          addService: "+ Add Service",
        },
        recent: {
          title: "Recent Branch Activity",
          subtitle: "Latest branch creation updates across the organization.",
          nameCol: "Branch Name",
        },
      },
      branches: {
        title: "Branches",
        subtitle: "Manage branches in your organization",
        addButton: "+ Add Branch",
        activeTableTitle: "Active Branches",
        pendingTableTitle: "Pending Branch Requests",
      },
      branchAdmins: {
        title: "Branch Admins",
        subtitle: "View and manage branch administrators grouped by branch",
        addFormTitle: "Add Branch Admin",
        addFormSubtitle: "Create a branch administrator for one of your branches",
        addFormButton: "Create Branch Admin",
        addFormButtonSubmitting: "Creating...",
      },
      addBranch: {
        title: "Add Branch",
        subtitle: "Create a new branch in your organization",
        nameLabel: "Branch Name",
        namePlaceholder: "e.g., Main Branch",
        codeLabel: "Branch Code",
        codePlaceholder: "e.g., BR-001",
        adminToggleLabel: "Enable Branch Admin Access",
        adminSectionTitle: "Branch Admin Details (Optional)",
        submitButton: "Create Branch",
        submittingButton: "Creating...",
      },
    },
    branchAdminPages: {
      dashboard: {
        roleLabel: "Branch Admin",
        pageTitle: "Branch Dashboard Overview",
        cards: {
          totalTokens: "Total Tokens Issued Today",
          waiting: "Waiting in Queue",
          capacity: "Today's Token Capacity",
          staff: "Active Staff Members",
        },
        charts: {
          peakTitle: "Peak Hours",
          peakSubtitle: "Tokens issued per hour from 8 AM to 5 PM",
          limitTitle: "Service Limit Progress",
          limitSubtitle: "Daily limit versus issued tokens by service",
        },
        monitor: {
          title: "Live Counter Monitor",
          subtitle: "Real-time Snapshot",
          serving: "Now Serving",
          staffLabel: "Staff",
          serviceLabel: "Service",
          emptyState: "No active counters available.",
        },
      },
      staff: {
        pageTitle: "Staff Management",
        pageSubtitle: "Manage staff members for your branch",
        addStaffBtn: "+ Add Staff",
        emptyStaff: "No staff users found",
        emptyBlockText: "No staff members",
        summaryTitle: "Staff Summary",
        summaryActive: "Active Staff",
        summaryInactive: "Inactive Staff",
        summaryUnassigned: "Unassigned Staff",
        slideOverTitle: "Staff Details",
        slideOverSubtitle: "Branch staff member details",
      },
      operations: {
        pageTitle: "Branch Operations",
        pageSubtitle: "Operations dashboard for",
        loadingText: "Loading operations dashboard...",
        servicesTitle: "Services",
        noServices: "No services found for this branch",
        activeCounters: "Active Counters",
        inactiveCounters: "Inactive Counters",
        addCounterBtn: "+ Add Counter",
        hideCounterBtn: "Hide Counter Form",
        counterNameLabel: "Counter Name",
        counterNamePlaceholder: "e.g., Counter A",
        createBtn: "Create",
        creatingBtn: "Creating...",
        noCounters: "No counters yet",
        counterCol: "Counter",
        staffCol: "Assigned Staff",
        noStaff: "No staff assigned",
        limitsTitle: "Daily Limits Management",
        branchLimitLabel: "Branch Limit",
        allocatedLabel: "Allocated Tokens",
        remainingLabel: "Remaining Tokens",
        noLimitServices: "No services found for daily limit management",
        serviceNameCol: "Service Name",
        limitCol: "Limit",
        estTimeCol: "Est. Time/Token (min)",
        actionCol: "Action",
        saveBtn: "Save",
        savingBtn: "Saving...",
        limitExceedError: "Cannot allocate tokens. Exceeds the branch total daily limit.",
      },
      branchDetails: {
        pageTitle: "Branch Details",
        pageSubtitle: "Branch information and operating hours for",
        sysInfoTitle: "System Information",
        orgLabel: "Organization",
        cityLabel: "City",
        addressLabel: "Address",
        contactLabel: "Contact",
        emailLabel: "Email",
        maxTokensLabel: "Max Daily Tokens",
        opHoursTitle: "Operating Hours",
        statusLabel: "Status",
        openTimeLabel: "Open Time",
        closeTimeLabel: "Close Time",
        saveBtn: "Save Hours",
        savingBtn: "Saving...",
        unlimitedText: "Unlimited",
      },
      addStaff: {
        pageTitle: "Add Staff",
        pageSubtitle: "Create a new staff user for your branch",
        createBtn: "Create Staff",
        creatingBtn: "Creating...",
      },
      
    },
    superAdminPages: {
      dashboard: {
        pageTitle: "Bank Network Overview",
        totalEntityTitle: "Total Banks",
        totalSubEntityTitle: "Total Branches",
        quickActionsSubtitle: "Common bank administration tasks.",
        addEntityLabel: "+ Add Bank Organization",
        reviewRequestsLabel: "Review Pending Branches",
        viewAllLabel: "View All Organizations",
        recentTitle: "Recently Onboarded Branches",
        recentSubtitle: "Latest 5 branches added to the bank network.",
        chartTitle: "Branches per Organization",
        chartSubtitle: "Branch distribution across organizations.",
        paths: {
          add: "/bank-super-admin/add-bank",
          requests: "/bank-super-admin/branch-requests",
          organizations: "/bank-super-admin/organizations",
        },
      },
      branchRequests: {
        pageTitle: "Branch Requests",
        pageSubtitle: "Review and manage pending branch requests for your bank network",
        tableTitle: "Pending Bank Requests",
        loadingText: "Loading pending branch requests...",
        noRequestsText: "No pending branch requests found.",
        slideOverTitle: "Branch Request Details",
        slideOverSubtitle: "Pending branch request overview",
        branchLabel: "Branch Name",
        orgLabel: "Organization",
      },
    },
  },
  hospital: {
    roleLabels: {
      ORGANIZATION_ADMIN: "District Admin",
    },
    sidebar: {
      branches: "Hospitals",
      branchAdmins: "Hospital Admins",
    },
    organizations: {
      pageTitle: "Districts",
      pageSubtitle: "Manage and view all registered districts",
      addLabel: "Add District",
      tableTitle: "Registered Districts",
    },
    branches: {
      pageTitle: "Hospital Management",
      pageSubtitle: "Manage and view all hospitals in the district",
      tableTitle: "Hospital Branches",
    },
    orgAdminPages: {
      addService: {
        title: "Add Service (Bulk)",
        subtitle: "Create a service for multiple hospitals at once",
        selectLabel: "Select Hospitals (Hold Ctrl/Cmd to select multiple)",
        selectedText: "hospitals",
        emptySelectionError: "Please select at least one hospital.",
      },
      services: {
        title: "Services",
        subtitle: "Manage services across your hospitals",
        addBtn: "+ Add Service",
        noData: "No hospitals found",
        divisionServicesTitle: "District Services",
        noDivisionServices: "No district services found.",
        branchCol: "Hospital Name",
        noBranchesOffer: "No hospitals offer this service.",
      },
      dashboard: {
        pageTitle: "District Dashboard Overview",
        roleLabel: "District Admin",
        cards: {
          branches: "Hospitals",
          requests: "Pending Requests",
          services: "Services",
          workforce: "Workforce",
        },
        charts: {
          statusTitle: "Hospital Status Overview",
          statusSubtitle: "Breakdown of hospital lifecycle status across the district.",
          topTitle: "Top Hospitals by Staff Size",
          topSubtitle: "Compare service volume for the busiest hospitals.",
        },
        quickActions: {
          title: "Quick Actions",
          subtitle: "Create and manage core district records.",
          addBranch: "+ Add New Hospital",
          addAdmin: "+ Add Hospital Admin",
          addService: "+ Add Service",
        },
        recent: {
          title: "Recent Hospital Activity",
          subtitle: "Latest hospital creation updates across the district.",
          nameCol: "Hospital Name",
        },
      },
      branches: {
        title: "Hospitals",
        subtitle: "Manage hospitals in your district",
        addButton: "+ Add Hospital",
        activeTableTitle: "Active Hospitals",
        pendingTableTitle: "Pending Hospital Requests",
      },
      branchAdmins: {
        title: "Hospital Admins",
        subtitle: "View and manage hospital administrators grouped by hospital",
        addFormTitle: "Add Hospital Admin",
        addFormSubtitle: "Create an administrator for one of your hospitals",
        addFormButton: "Create Hospital Admin",
        addFormButtonSubmitting: "Creating...",
      },
      addBranch: {
        title: "Add Hospital",
        subtitle: "Create a new hospital in your district",
        nameLabel: "Hospital Name",
        namePlaceholder: "e.g., General Hospital",
        codeLabel: "Hospital Code",
        codePlaceholder: "e.g., GH-001",
        adminToggleLabel: "Enable Hospital Admin Access",
        adminSectionTitle: "Hospital Admin Details (Optional)",
        submitButton: "Create Hospital",
        submittingButton: "Creating...",
      },
    },
    branchAdminPages: {
      dashboard: {
        roleLabel: "Hospital Admin",
        pageTitle: "Hospital Dashboard Overview",
        cards: {
          totalTokens: "Total Appointments Today",
          waiting: "Waiting in Queue",
          capacity: "Today's Appointment Capacity",
          staff: "Active Medical Staff",
        },
        charts: {
          peakTitle: "Peak Hours",
          peakSubtitle: "Appointments per hour from 8 AM to 5 PM",
          limitTitle: "Department Limit Progress",
          limitSubtitle: "Daily limit versus appointments by department",
        },
        monitor: {
          title: "Live Room Monitor",
          subtitle: "Real-time Snapshot",
          serving: "Now Serving",
          staffLabel: "Doctor/Staff",
          serviceLabel: "Department",
          emptyState: "No active rooms available.",
        },
      },
      staff: {
        pageTitle: "Staff & Doctors",
        pageSubtitle: "Manage medical and support staff for your hospital",
        addStaffBtn: "+ Add Support Staff",
        addDoctorBtn: "+ Add Doctor",
        emptyStaff: "No staff or doctors found",
        emptyBlockText: "No staff or doctors",
        summaryTitle: "Staff & Doctors Summary",
        summaryActive: "Active Members",
        summaryInactive: "Inactive Members",
        summaryUnassigned: "Unassigned Members",
        slideOverTitle: "Member Details",
        slideOverSubtitle: "Hospital staff or doctor details",
      },
      operations: {
        pageTitle: "Hospital Operations",
        pageSubtitle: "Operations dashboard for",
        loadingText: "Loading operations dashboard...",
        servicesTitle: "Departments",
        noServices: "No departments found for this hospital",
        activeCounters: "Active Rooms",
        inactiveCounters: "Inactive Rooms",
        addCounterBtn: "+ Add Room",
        hideCounterBtn: "Hide Room Form",
        counterNameLabel: "Room Name",
        counterNamePlaceholder: "e.g., Room 101",
        createBtn: "Create",
        creatingBtn: "Creating...",
        noCounters: "No rooms yet",
        counterCol: "Room",
        staffCol: "Assigned Doctor",
        noStaff: "No doctor assigned",
        limitsTitle: "Daily Appointment Limits",
        branchLimitLabel: "Hospital Limit",
        allocatedLabel: "Allocated Appointments",
        remainingLabel: "Remaining Appointments",
        noLimitServices: "No departments found for daily limit management",
        serviceNameCol: "Department Name",
        limitCol: "Limit",
        estTimeCol: "Est. Time/Patient (min)",
        actionCol: "Action",
        saveBtn: "Save",
        savingBtn: "Saving...",
        limitExceedError: "Cannot allocate appointments. Exceeds the hospital total daily limit.",
      },
      branchDetails: {
        pageTitle: "Hospital Details",
        pageSubtitle: "Hospital information and operating hours for",
        sysInfoTitle: "System Information",
        orgLabel: "District",
        cityLabel: "City",
        addressLabel: "Address",
        contactLabel: "Contact",
        emailLabel: "Email",
        maxTokensLabel: "Max Daily Appointments",
        opHoursTitle: "Operating Hours",
        statusLabel: "Status",
        openTimeLabel: "Open Time",
        closeTimeLabel: "Close Time",
        saveBtn: "Save Hours",
        savingBtn: "Saving...",
        unlimitedText: "Unlimited",
      },
      addStaff: {
        pageTitle: "Add Support Staff",
        pageSubtitle: "Create a new support staff user for your hospital",
        createBtn: "Create Staff",
        creatingBtn: "Creating...",
      },
      
    },
    superAdminPages: {
      dashboard: {
        pageTitle: "Hospital Network Overview",
        totalEntityTitle: "Total Districts",
        totalSubEntityTitle: "Total Hospitals",
        quickActionsSubtitle: "Common hospital administration tasks.",
        addEntityLabel: "+ Add District",
        reviewRequestsLabel: "Review Hospital Requests",
        viewAllLabel: "View All Districts",
        recentTitle: "Recently Onboarded Hospitals",
        recentSubtitle: "Latest 5 hospitals added to the network.",
        chartTitle: "Hospitals per District",
        chartSubtitle: "Hospital distribution across districts.",
        paths: {
          add: "/hospital-super-admin/add-hospital",
          requests: "/hospital-super-admin/branch-requests",
          organizations: "/hospital-super-admin/registered-hospitals",
        },
      },
      branchRequests: {
        pageTitle: "Hospital Requests",
        pageSubtitle: "Review and manage pending hospital requests for your hospital network",
        tableTitle: "Pending Hospital Requests",
        loadingText: "Loading pending hospital requests...",
        noRequestsText: "No pending hospital requests found.",
        slideOverTitle: "Hospital Request Details",
        slideOverSubtitle: "Pending hospital request overview",
        branchLabel: "Hospital Name",
        orgLabel: "District",
      },
    },
  },
  police: {
    roleLabels: {
      ORGANIZATION_ADMIN: "Division Admin",
    },
    sidebar: {
      branches: "Police Stations",
      branchAdmins: "Station Admins",
    },
    organizations: {
      pageTitle: "Police Divisions",
      pageSubtitle: "Manage and view all registered divisions",
      addLabel: "Add Division",
      tableTitle: "Registered Networks",
    },
    branches: {
      pageTitle: "Police Stations",
      pageSubtitle: "Manage and view all police stations in the division",
      tableTitle: "Police Stations",
    },
    orgAdminPages: {
      addService: {
        title: "Add Service (Bulk)",
        subtitle: "Create a service for multiple stations at once",
        selectLabel: "Select Stations (Hold Ctrl/Cmd to select multiple)",
        selectedText: "stations",
        emptySelectionError: "Please select at least one station.",
      },
      services: {
        title: "Services",
        subtitle: "Manage services across your stations",
        addBtn: "+ Add Service",
        noData: "No stations found",
        divisionServicesTitle: "Division Services",
        noDivisionServices: "No division services found.",
        branchCol: "Station Name",
        noBranchesOffer: "No stations offer this service.",
      },
      dashboard: {
        pageTitle: "Division Dashboard Overview",
        roleLabel: "Division Admin",
        cards: {
          branches: "Police Stations",
          requests: "Pending Requests",
          services: "Services",
          workforce: "Workforce",
        },
        charts: {
          statusTitle: "Station Status Overview",
          statusSubtitle: "Breakdown of station lifecycle status across the division.",
          topTitle: "Top Stations by Staff Size",
          topSubtitle: "Compare service volume for the busiest stations.",
        },
        quickActions: {
          title: "Quick Actions",
          subtitle: "Create and manage core division records.",
          addBranch: "+ Add New Station",
          addAdmin: "+ Add Station Admin",
          addService: "+ Add Service",
        },
        recent: {
          title: "Recent Station Activity",
          subtitle: "Latest station creation updates across the division.",
          nameCol: "Station Name",
        },
      },
      branches: {
        title: "Police Stations",
        subtitle: "Manage police stations in your division",
        addButton: "+ Add Police Station",
        activeTableTitle: "Active Police Stations",
        pendingTableTitle: "Pending Police Station Requests",
      },
      branchAdmins: {
        title: "Station Admins",
        subtitle: "View and manage station administrators grouped by station",
        addFormTitle: "Add Station Admin",
        addFormSubtitle: "Create an administrator for one of your stations",
        addFormButton: "Create Station Admin",
        addFormButtonSubmitting: "Creating...",
      },
      addBranch: {
        title: "Add Police Station",
        subtitle: "Create a new police station in your division",
        nameLabel: "Station Name",
        namePlaceholder: "e.g., Central Police Station",
        codeLabel: "Station Code",
        codePlaceholder: "e.g., PS-001",
        adminToggleLabel: "Enable Station Admin Access",
        adminSectionTitle: "Station Admin Details (Optional)",
        submitButton: "Create Station",
        submittingButton: "Creating...",
      },
    },
    branchAdminPages: {
      dashboard: {
        roleLabel: "Station Admin",
        pageTitle: "Station Dashboard Overview",
        cards: {
          totalTokens: "Total Tokens Issued Today",
          waiting: "Waiting in Queue",
          capacity: "Today's Token Capacity",
          staff: "Active Officers",
        },
        charts: {
          peakTitle: "Peak Hours",
          peakSubtitle: "Tokens issued per hour from 8 AM to 5 PM",
          limitTitle: "Service Limit Progress",
          limitSubtitle: "Daily limit versus issued tokens by service desk",
        },
        monitor: {
          title: "Live Desk Monitor",
          subtitle: "Real-time Snapshot",
          serving: "Now Serving",
          staffLabel: "Officer",
          serviceLabel: "Desk/Service",
          emptyState: "No active desks available.",
        },
      },
      staff: {
        pageTitle: "Officers & Staff",
        pageSubtitle: "Manage officers and support staff for your station",
        addStaffBtn: "+ Add Officer/Staff",
        emptyStaff: "No officers or staff found",
        emptyBlockText: "No officers or staff",
        summaryTitle: "Officer & Staff Summary",
        summaryActive: "Active Officers",
        summaryInactive: "Inactive Officers",
        summaryUnassigned: "Unassigned Officers",
        slideOverTitle: "Officer/Staff Details",
        slideOverSubtitle: "Station personnel details",
      },
      operations: {
        pageTitle: "Station Operations",
        pageSubtitle: "Operations dashboard for",
        loadingText: "Loading operations dashboard...",
        servicesTitle: "Services",
        noServices: "No services found for this station",
        activeCounters: "Active Desks",
        inactiveCounters: "Inactive Desks",
        addCounterBtn: "+ Add Desk",
        hideCounterBtn: "Hide Desk Form",
        counterNameLabel: "Desk Name",
        counterNamePlaceholder: "e.g., Desk 1",
        createBtn: "Create",
        creatingBtn: "Creating...",
        noCounters: "No desks yet",
        counterCol: "Desk",
        staffCol: "Assigned Officer",
        noStaff: "No officer assigned",
        limitsTitle: "Daily Limits Management",
        branchLimitLabel: "Station Limit",
        allocatedLabel: "Allocated Tokens",
        remainingLabel: "Remaining Tokens",
        noLimitServices: "No services found for daily limit management",
        serviceNameCol: "Service Name",
        limitCol: "Limit",
        estTimeCol: "Est. Time/Token (min)",
        actionCol: "Action",
        saveBtn: "Save",
        savingBtn: "Saving...",
        limitExceedError: "Cannot allocate tokens. Exceeds the station total daily limit.",
      },
      branchDetails: {
        pageTitle: "Station Details",
        pageSubtitle: "Station information and operating hours for",
        sysInfoTitle: "System Information",
        orgLabel: "Division",
        cityLabel: "City",
        addressLabel: "Address",
        contactLabel: "Contact",
        emailLabel: "Email",
        maxTokensLabel: "Max Daily Tokens",
        opHoursTitle: "Operating Hours",
        statusLabel: "Status",
        openTimeLabel: "Open Time",
        closeTimeLabel: "Close Time",
        saveBtn: "Save Hours",
        savingBtn: "Saving...",
        unlimitedText: "Unlimited",
      },
      addStaff: {
        pageTitle: "Add Officer/Staff",
        pageSubtitle: "Create a new officer or staff user for your station",
        createBtn: "Create User",
        creatingBtn: "Creating...",
      },
    },
    superAdminPages: {
      dashboard: {
        pageTitle: "Police Network Overview",
        totalEntityTitle: "Total Main Divisions",
        totalSubEntityTitle: "Total Police Stations",
        quickActionsSubtitle: "Common police administration tasks.",
        addEntityLabel: "+ Add Main Division",
        reviewRequestsLabel: "Review Station Requests",
        viewAllLabel: "View All Divisions",
        recentTitle: "Recently Onboarded Police Stations",
        recentSubtitle: "Latest 5 police stations added to the network.",
        chartTitle: "Stations per Division",
        chartSubtitle: "Police station distribution across divisions.",
        paths: {
          add: "/police-super-admin/add-main-division",
          requests: "/police-super-admin/branch-requests",
          organizations: "/police-super-admin/main-division",
        },
      },
      branchRequests: {
        pageTitle: "Police Station Requests",
        pageSubtitle: "Review and manage pending station requests for your police network",
        tableTitle: "Pending Police Station Requests",
        loadingText: "Loading pending station requests...",
        noRequestsText: "No pending station requests found.",
        slideOverTitle: "Station Request Details",
        slideOverSubtitle: "Pending station request overview",
        branchLabel: "Station Name",
        orgLabel: "Division",
      },
    },
  },
};